services:
  postgres:
    image: postgres:16-alpine
    container_name: amazon_dw
    env_file:
      - ./credential.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - ./db/trigger.sql:/docker-entrypoint-initdb.d/02_trigger.sql:ro

volumes:
  pgdata:
